name: CI - Test bn Utility

on:
	push:
		branches: [ "main" ] 
jobs:
	test: 
		runs-on: ubuntu-latest 
		steps:
		- uses: actions/checkout@v4 
  
		- name: Run_Tests 
			run: ./test_script > test_results.txt 
		- name: Upload Test Results 
			if: ${{ always() }} 
			subtask returned a fail code
			uses: actions/upload-artifact@v4 
			with:
				name: Test Results 
				path: ./test_results.txt
